fixed npy problem, refactored recog script
samaritan-security/samaritan-backend pull request #52
Opened 2020-03-12 20:29 UTC by katebrune

figured out how to get nparrays out of db without changing their data:
![image](https://user-images.githubusercontent.com/31379789/76563407-55b38100-6475-11ea-8e17-2190a7ff9c0a.png)

to figure this out, i refactored RecogScript.process_video_to_encode() by putting stuff in separate functions so i could individually test what was going on and pinpoint the problem. these functions are in FacialRecog.py (get_frame, get_face_encodings, compare_encodings). I also added tests for these functions in tests/facial_recog_tests.py.

additionally, i started looking over check_encodings in RecogScript and realized when we don't know who is in an image we would just add one person, but it could be two, so i made a function get_images_and_encodings (in FacialRecog.py) that takes a frame and returns encodings and images cropped around individual faces in the frame. This could be problematic if one person in the frame is in the system and one person isn't, because it would add both, so we should eventaully move this so we break the frame up by faces (cropped images) before we begin the facial recog comparisons.

2020-03-12 20:32 UTC, gould-ann requested changes

2020-03-12 20:32 UTC, gould-ann commented on RecogScript.py
> +                    for encoding in unknown encodings:
heads up-- this is invalid syntax

2020-03-12 20:55 UTC, gould-ann commented on FacialRecog.py
> +        iterable = formatted_npy_str.split() #make string values iterable
also good job on this!

2020-03-12 20:56 UTC, gould-ann approved these changes
😍 i didnt know i could love code until I saw this code

2020-03-13 00:33 UTC, rgoluch reviewed
awesome job! looks great!

2020-03-13 00:33 UTC, merged